services:
  - type: web
    name: zero-trust-security
    env: python
    plan: free
    buildCommand: "npm install --prefix frontend && npm run build --prefix frontend && pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: MONGO_URL
        sync: false
      - key: MAILERSEND_API_KEY
        sync: false
      - key: MAILERSEND_SENDER
        sync: false
      - key: NODE_VERSION
        value: 18.16.0
      - key: VITE_API_URL
        value: "" # Empty means same origin (producion build serves backend and frontend together)
