services:
  - type: web
    name: zero-trust-security
    env: python
    plan: free
    buildCommand: "npm install --prefix frontend && npm run build --prefix frontend && pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGO_URL
        sync: false
      - key: MAILERSEND_API_KEY
        sync: false
      - key: MAILERSEND_SENDER
        sync: false
      - key: NODE_VERSION
        value: 18.16.0
      - key: PYTHON_VERSION
        value: 3.11.0 # Use a stable known version
      - key: VITE_API_URL
        value: ""
